Repository kong-dak/kong-dak, pull requests merged in 2025-02, with the labels that each got.

#81 Diary Error fix - local과 Hibernate 설정 확인
  backend/src/main/java/com/kongdak/controller/DatabaseConfig.java
  backend/src/main/java/com/kongdak/domain/dailyquestion/DailyQuestionService.java
Labels: bug, enhancement

#82 DailyAnswer FETCH 메서드 추가
  backend/src/main/java/com/kongdak/controller/DailyQuestionController.java
  backend/src/main/java/com/kongdak/controller/dto/request/DailyAnswerUpdateRequest.java
  backend/src/main/java/com/kongdak/controller/dto/response/DailyAnswerCreateResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/DailyAnswerUpdateResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/DailyQuestionWithAnswersResponse.java
  backend/src/main/java/com/kongdak/domain/dailyquestion/DailyAnswer.java
  backend/src/main/java/com/kongdak/domain/dailyquestion/DailyQuestionService.java
  backend/src/main/java/com/kongdak/global/exception/ErrorCode.java
Labels: enhancement

#84 데일리 질문 데이터 연동
  frontend/app/(tabs)/index.tsx
  frontend/app/(tabs)/question/index.tsx
  frontend/app/(tabs)/question/viewanswer.tsx
  frontend/app/(tabs)/question/writeanswer.tsx
  frontend/app/index.tsx
  frontend/app/login/setnick.tsx
  frontend/app/mycode/index.tsx
  frontend/app/mycode/inputcode.tsx
  frontend/assets/apis/couples.ts
  frontend/assets/apis/daily-questions.ts
  frontend/assets/apis/members.ts
  frontend/assets/types/question/questionModels.ts
  frontend/assets/utils/http-common.ts
  frontend/package-lock.json
Labels: documentation

#85 Logging Aspect 수정
  backend/src/main/java/com/kongdak/global/aop/LoggingAspect.java
Labels: duplicate, enhancement

#87 JWT 토큰 관련 에러 커스텀 및 BaseResponse 적용
  backend/src/main/java/com/kongdak/config/SecurityConfig.java
  backend/src/main/java/com/kongdak/global/security/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/com/kongdak/global/security/jwt/JwtTokenProvider.java
  backend/src/main/java/com/kongdak/global/security/jwt/OAuth2SuccessHandler.java
Labels: documentation, enhancement

#88 swagger 관련 엔드포인트 수정
  backend/src/main/java/com/kongdak/global/security/jwt/JwtAuthenticationFilter.java
Labels: bug

#91 앱 진입 시 자동 로그인 연동
  frontend/app/(tabs)/question/writeanswer.tsx
  frontend/app/index.tsx
  frontend/assets/apis/auth.ts
  frontend/assets/utils/http-common.ts
  frontend/assets/utils/httpHandler.ts
  frontend/package-lock.json
  frontend/package.json
Labels: documentation

#93 카카오 로그인 SDK로 전환
  backend/src/main/java/com/kongdak/config/SecurityConfig.java
  backend/src/main/java/com/kongdak/controller/AuthController.java
  backend/src/main/java/com/kongdak/controller/dto/request/SocialLoginRequest.java
  backend/src/main/java/com/kongdak/global/exception/ErrorCode.java
  backend/src/main/java/com/kongdak/global/security/jwt/sdk/SimpleJwtTokenProvider.java
  backend/src/main/java/com/kongdak/global/security/jwt/sdk/SocialLoginService.java
Labels: enhancement

#94 PathVariable parameter 명시
  backend/Dockerfile
  backend/src/main/java/com/kongdak/controller/AuthController.java
Labels: enhancement

#95 Inner Class 분리
  backend/src/main/java/com/kongdak/global/security/jwt/sdk/KakaoAccount.java
  backend/src/main/java/com/kongdak/global/security/jwt/sdk/KakaoUserInfo.java
  backend/src/main/java/com/kongdak/global/security/jwt/sdk/SocialLoginService.java
Labels: enhancement

#96 로깅 시스템 구현을 위해 ELK Stack 도입
  backend/build.gradle
  backend/src/main/java/com/kongdak/controller/AuthController.java
  backend/src/main/java/com/kongdak/controller/CoupleController.java
  backend/src/main/java/com/kongdak/domain/couple/CoupleMatchRedisRepository.java
  backend/src/main/java/com/kongdak/domain/couple/CoupleService.java
  backend/src/main/java/com/kongdak/domain/dailyquestion/DailyQuestionService.java
  backend/src/main/java/com/kongdak/domain/notification/SseEmitterService.java
  backend/src/main/java/com/kongdak/global/aop/LoggingAspect.java
  backend/src/main/java/com/kongdak/global/exception/ErrorCode.java
  backend/src/main/java/com/kongdak/global/security/jwt/sdk/SocialLoginService.java
  backend/src/main/resources/logback-spring.xml
  elk/logstash/config/logstash.yml
  elk/logstash/pipeline/kongdak.conf
Labels: enhancement

#97 chore: docker-compose, Dockerfile 추가
  docker-compose.yml
  frontend/Dockerfile
Labels: documentation, enhancement

#98 LoggingAspect AOP 수정
  backend/src/main/java/com/kongdak/global/aop/LoggingAspect.java
  backend/src/main/java/com/kongdak/global/security/jwt/JwtAuthenticationFilter.java
Labels: bug, enhancement

#99 Social 로그인 서비스 에러처리 세분화
  backend/src/main/java/com/kongdak/global/exception/ErrorCode.java
  backend/src/main/java/com/kongdak/global/security/jwt/sdk/SocialLoginService.java
Labels: bug

#101 ELK 스택을 Prometheus와 Grafana로 변경
  backend/build.gradle
  backend/src/main/resources/logback-spring.xml
  docker-compose.yml
  prometheus/prometheus.yml
Labels: enhancement

#102 Social 로그인 서비스 에러처리 세분화
  backend/src/main/java/com/kongdak/global/security/jwt/sdk/SocialLoginService.java
Labels: bug

#103 Kakao API UserInfo 요청 형식 변경
  backend/src/main/java/com/kongdak/global/security/jwt/sdk/KakaoAccount.java
  backend/src/main/java/com/kongdak/global/security/jwt/sdk/KakaoUserInfo.java
  backend/src/main/java/com/kongdak/global/security/jwt/sdk/SocialLoginService.java
Labels: bug

#104 AccessToken, RefreshToken 발급 방식 변경
  backend/src/main/java/com/kongdak/global/security/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/com/kongdak/global/security/jwt/sdk/SimpleJwtTokenProvider.java
Labels: enhancement

#106 OAuth 로그인시 Nickname 변경 여부 추가
  backend/src/main/java/com/kongdak/domain/member/Member.java
  backend/src/main/java/com/kongdak/domain/member/MemberService.java
  backend/src/main/java/com/kongdak/global/security/jwt/TokenPairResponse.java
  backend/src/main/java/com/kongdak/global/security/jwt/sdk/SimpleJwtTokenProvider.java
Labels: enhancement

#108 JwtTokenProvider 주석처리
  backend/src/main/java/com/kongdak/global/security/jwt/JwtTokenProvider.java
Labels: bug

#107 다이어리, 자동 로그인 API 연동 및 구현
  frontend/app/(tabs)/calendar/index.tsx
  frontend/app/(tabs)/diary/index.tsx
  frontend/app/(tabs)/question/index.tsx
  frontend/app/index.tsx
  frontend/app/login/kakao.tsx
  frontend/app/login/setnick.tsx
  frontend/app/write/edit.tsx
  frontend/app/write/index.tsx
  frontend/assets/apis/auth.ts
  frontend/assets/apis/calendars.ts
  frontend/assets/apis/diary.ts
  frontend/assets/types/diary/diaryModels.ts
  frontend/assets/utils/http-common.ts
  frontend/components/ui/CalendarDetailList.tsx
  frontend/components/ui/CustomCalendarDiary.tsx
  frontend/components/ui/DropDownPicker.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: documentation

#109 OAuth2SuccessHandler 주석처리
  backend/src/main/java/com/kongdak/global/security/jwt/OAuth2SuccessHandler.java
Labels: bug

#111 캘린더 API 연동
  frontend/app/(tabs)/calendar/index.tsx
  frontend/app/(tabs)/diary/index.tsx
  frontend/app/calenderregist/index.tsx
  frontend/app/write/edit.tsx
  frontend/app/write/index.tsx
  frontend/assets/apis/calendars.ts
  frontend/assets/apis/diary.ts
  frontend/assets/types/calendar/calendarModels.ts
  frontend/assets/types/type.ts
  frontend/assets/utils/calendar.ts
  frontend/assets/utils/http-common.ts
  frontend/components/common/AppButton.tsx
  frontend/components/ui/CalendarDetailList.tsx
  frontend/components/ui/CustomCalendarMini.tsx
  frontend/components/ui/DiaryItem.tsx
  frontend/components/ui/DropDownPicker.tsx
  frontend/components/ui/TimePicker.tsx
Labels: documentation
