Repository kong-dak/kong-dak, pull requests merged in 2025-01, with the labels that each got.

#34 커플 다이어리 기능 개발
  backend/src/main/java/com/kongdak/controller/DailyQuestionController.java
  backend/src/main/java/com/kongdak/controller/DiaryController.java
  backend/src/main/java/com/kongdak/controller/dto/request/CreateDiaryRequest.java
  backend/src/main/java/com/kongdak/controller/dto/request/DecorationCreateRequest.java
  backend/src/main/java/com/kongdak/controller/dto/request/DecorationUpdateRequest.java
  backend/src/main/java/com/kongdak/controller/dto/request/UpdateDiaryRequest.java
  backend/src/main/java/com/kongdak/controller/dto/response/DailyQuestionResponseDto.java
  backend/src/main/java/com/kongdak/controller/dto/response/DecorationResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/DiaryDetailResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/DiaryListResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/PhotoResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/SearchDiaryResponse.java
  backend/src/main/java/com/kongdak/domain/couple/CoupleRepository.java
  backend/src/main/java/com/kongdak/domain/diary/DecorationType.java
  backend/src/main/java/com/kongdak/domain/diary/Diary.java
  backend/src/main/java/com/kongdak/domain/diary/DiaryDecoration.java
  backend/src/main/java/com/kongdak/domain/diary/DiaryDecorationRepository.java
  backend/src/main/java/com/kongdak/domain/diary/DiaryPhoto.java
  backend/src/main/java/com/kongdak/domain/diary/DiaryPhotoRepository.java
  backend/src/main/java/com/kongdak/domain/diary/DiaryRepository.java
  backend/src/main/java/com/kongdak/domain/diary/DiaryService.java
  backend/src/main/java/com/kongdak/domain/diary/Emotion.java
  backend/src/main/java/com/kongdak/domain/diary/Weather.java
  backend/src/main/java/com/kongdak/global/exception/ErrorCode.java
  backend/src/main/java/com/kongdak/global/redis/RedisConfig.java
  backend/src/main/java/com/kongdak/global/redis/RedisLockRepository.java
Labels: duplicate

#40 feat: 지도 화면 구성 및 검색 api 연결
  frontend/app/(tabs)/calendar/mapscreen.tsx
  frontend/app/calenderregist/index.tsx
  frontend/assets/apis/maps.ts
  frontend/components/ui/MapScreen.tsx
  frontend/components/ui/MapSearchBar.tsx
  frontend/hooks/useSearch.ts
Labels: documentation

#42 refactor: 네이버 Search API를 카카오 Search API로 변경
  backend/src/main/java/com/kongdak/controller/MapController.java
  backend/src/main/java/com/kongdak/controller/dto/response/KakaoLocalSearchResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/NaverSearchApiResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/NaverSearchResponse.java
  backend/src/main/java/com/kongdak/domain/calendar/MapService.java
  backend/src/main/java/com/kongdak/domain/map/MapService.java
Labels: documentation

#45 OAuth2 & JWT 인증/인가 구현
  backend/build.gradle
  backend/src/main/java/com/kongdak/config/CustomOAuth2User.java
  backend/src/main/java/com/kongdak/config/CustomOAuth2UserService.java
  backend/src/main/java/com/kongdak/config/RedisConfig.java
  backend/src/main/java/com/kongdak/config/SecurityConfig.java
  backend/src/main/java/com/kongdak/controller/AuthController.java
  backend/src/main/java/com/kongdak/controller/CoupleController.java
  backend/src/main/java/com/kongdak/controller/MemberController.java
  backend/src/main/java/com/kongdak/controller/dto/request/TokenRefreshRequest.java
  backend/src/main/java/com/kongdak/controller/dto/response/TokenRefreshResponse.java
  backend/src/main/java/com/kongdak/global/exception/ErrorCode.java
  backend/src/main/java/com/kongdak/global/security/jwt/CustomUserDetails.java
  backend/src/main/java/com/kongdak/global/security/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/com/kongdak/global/security/jwt/JwtTokenProvider.java
  backend/src/main/java/com/kongdak/global/security/jwt/OAuth2SuccessHandler.java
  backend/src/main/java/com/kongdak/global/security/jwt/RefreshTokenRepository.java
  backend/src/main/java/com/kongdak/global/security/jwt/TokenResponse.java
  backend/src/main/resources/logback-spring.xml
  frontend/assets/types/type.ts
Labels: documentation, duplicate

#51 Swagger API 도입
  backend/build.gradle
  backend/src/main/java/com/kongdak/config/SecurityConfig.java
  backend/src/main/java/com/kongdak/config/SwaggerConfig.java
  backend/src/main/java/com/kongdak/controller/AuthController.java
  backend/src/main/java/com/kongdak/controller/CalendarController.java
  backend/src/main/java/com/kongdak/controller/CoupleController.java
  backend/src/main/java/com/kongdak/controller/DailyQuestionController.java
  backend/src/main/java/com/kongdak/controller/DiaryController.java
  backend/src/main/java/com/kongdak/controller/MapController.java
  backend/src/main/java/com/kongdak/controller/MemberController.java
  backend/src/main/java/com/kongdak/controller/dto/request/CoupleConnectRequest.java
  backend/src/main/java/com/kongdak/controller/dto/request/CreateDiaryRequest.java
  backend/src/main/java/com/kongdak/controller/dto/request/DailyAnswerRequest.java
  backend/src/main/java/com/kongdak/controller/dto/request/DailyAnswerRequestDto.java
  backend/src/main/java/com/kongdak/controller/dto/request/DecorationCreateRequest.java
  backend/src/main/java/com/kongdak/controller/dto/request/DecorationUpdateRequest.java
  backend/src/main/java/com/kongdak/controller/dto/request/EmojiRequest.java
  backend/src/main/java/com/kongdak/controller/dto/request/EmojiRequestDto.java
  backend/src/main/java/com/kongdak/controller/dto/request/MemberCreateRequest.java
  backend/src/main/java/com/kongdak/controller/dto/request/ReplyRequest.java
  backend/src/main/java/com/kongdak/controller/dto/request/ReplyRequestDto.java
  backend/src/main/java/com/kongdak/controller/dto/request/ScheduleCreateRequest.java
  backend/src/main/java/com/kongdak/controller/dto/request/TokenRefreshRequest.java
  backend/src/main/java/com/kongdak/controller/dto/request/UpdateDiaryRequest.java
  backend/src/main/java/com/kongdak/controller/dto/request/UpdateNicknameRequest.java
  backend/src/main/java/com/kongdak/controller/dto/response/CalendarResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/CoupleInfo.java
  backend/src/main/java/com/kongdak/controller/dto/response/CoupleResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/DailyAnswerResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/DailyAnswerResponseDto.java
  backend/src/main/java/com/kongdak/controller/dto/response/DailyQuestionResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/DailyQuestionResponseDto.java
  backend/src/main/java/com/kongdak/controller/dto/response/DecorationResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/DiaryCreateResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/DiaryDetailResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/DiaryListResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/HolidayResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/MemberResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/MonthlyScheduleResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/PhotoResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/ReplyResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/ReplyResponseDto.java
  backend/src/main/java/com/kongdak/controller/dto/response/ScheduleDetailResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/ScheduleResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/SearchDiaryResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/TokenRefreshResponse.java
  backend/src/main/java/com/kongdak/domain/calendar/ScheduleCategory.java
  backend/src/main/java/com/kongdak/domain/dailyquestion/DailyQuestionService.java
  backend/src/main/java/com/kongdak/domain/diary/Emotion.java
  backend/src/main/java/com/kongdak/domain/diary/Weather.java
  backend/src/main/java/com/kongdak/global/exception/ErrorCode.java
  backend/src/main/java/com/kongdak/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/kongdak/global/redis/RedisConfig.java
  backend/src/main/java/com/kongdak/global/response/ApiResponse.java
  backend/src/main/java/com/kongdak/global/response/BaseResponse.java
  backend/src/main/java/com/kongdak/global/security/jwt/CustomOAuth2User.java
  backend/src/main/java/com/kongdak/global/security/jwt/CustomOAuth2UserService.java
  backend/src/main/java/com/kongdak/global/security/jwt/JwtTokenProvider.java
  backend/src/main/java/com/kongdak/global/security/jwt/OAuth2SuccessHandler.java
Labels: duplicate

#53 개발 환경 Cors Config
  backend/src/main/java/com/kongdak/config/SecurityConfig.java
Labels: enhancement

#54 JWT 처리 및 email 로직 변경
  backend/src/main/java/com/kongdak/config/SecurityConfig.java
  backend/src/main/java/com/kongdak/controller/MemberController.java
  backend/src/main/java/com/kongdak/domain/member/MemberService.java
  backend/src/main/java/com/kongdak/domain/member/OAuthProvider.java
  backend/src/main/java/com/kongdak/global/exception/ErrorCode.java
  backend/src/main/java/com/kongdak/global/security/jwt/CustomOAuth2UserService.java
  backend/src/main/java/com/kongdak/global/security/jwt/JwtTokenProvider.java
Labels: enhancement

#55 AOP 및 logback 설정 간소화
  backend/build.gradle
  backend/src/main/java/com/kongdak/global/aop/LoggingAspect.java
  backend/src/main/resources/logback-spring.xml
Labels: enhancement

#58 @Table 도입
  backend/.gitignore
  backend/src/main/java/com/kongdak/controller/AuthController.java
  backend/src/main/java/com/kongdak/controller/CalendarController.java
  backend/src/main/java/com/kongdak/controller/MemberController.java
  backend/src/main/java/com/kongdak/domain/calendar/Calendar.java
  backend/src/main/java/com/kongdak/domain/calendar/Holiday.java
  backend/src/main/java/com/kongdak/domain/diary/Diary.java
  backend/src/main/java/com/kongdak/domain/diary/DiaryDecoration.java
  backend/src/main/java/com/kongdak/domain/diary/DiaryPhoto.java
  backend/src/main/java/com/kongdak/domain/member/Member.java
  backend/src/main/java/com/kongdak/domain/member/MemberService.java
  backend/src/main/java/com/kongdak/global/security/jwt/JwtTokenProvider.java
  backend/src/main/java/com/kongdak/global/security/jwt/TokenPairResponse.java
Labels: enhancement

#59 커플 매칭 및 실시간 알림 시스템 구현(SSE)
  backend/src/main/java/com/kongdak/controller/CoupleController.java
  backend/src/main/java/com/kongdak/controller/DailyQuestionController.java
  backend/src/main/java/com/kongdak/controller/DiaryController.java
  backend/src/main/java/com/kongdak/controller/NotificationController.java
  backend/src/main/java/com/kongdak/controller/dto/request/ConnectCodeRequest.java
  backend/src/main/java/com/kongdak/controller/dto/request/CoupleMatchRequest.java
  backend/src/main/java/com/kongdak/controller/dto/response/CoupleMatchCodeResponse.java
  backend/src/main/java/com/kongdak/domain/couple/Couple.java
  backend/src/main/java/com/kongdak/domain/couple/CoupleMatchRedisRepository.java
  backend/src/main/java/com/kongdak/domain/couple/CoupleService.java
  backend/src/main/java/com/kongdak/domain/notification/NotificationMessage.java
  backend/src/main/java/com/kongdak/domain/notification/NotificationType.java
  backend/src/main/java/com/kongdak/domain/notification/SseEmitterService.java
  backend/src/main/java/com/kongdak/global/exception/ErrorCode.java
  backend/src/main/java/com/kongdak/global/security/jwt/CustomUserDetails.java
Labels: enhancement

#60 커플 관련 테스트(Swagger)
  backend/src/main/java/com/kongdak/controller/CoupleController.java
  backend/src/main/java/com/kongdak/domain/calendar/Calendar.java
  backend/src/main/java/com/kongdak/domain/couple/Couple.java
  backend/src/main/java/com/kongdak/domain/couple/CoupleMatchRedisRepository.java
  backend/src/main/java/com/kongdak/domain/couple/CoupleService.java
  backend/src/main/java/com/kongdak/global/security/jwt/CustomOAuth2User.java
  backend/src/main/java/com/kongdak/global/security/jwt/CustomOAuth2UserService.java
  backend/src/main/java/com/kongdak/global/security/jwt/JwtTokenProvider.java
Labels: duplicate, enhancement

#64 전반적인 응답 형식 표준화 및 Member-Couple 관계 개선
  backend/src/main/java/com/kongdak/controller/CalendarController.java
  backend/src/main/java/com/kongdak/controller/CoupleController.java
  backend/src/main/java/com/kongdak/controller/DailyQuestionController.java
  backend/src/main/java/com/kongdak/controller/DiaryController.java
  backend/src/main/java/com/kongdak/controller/MemberController.java
  backend/src/main/java/com/kongdak/controller/dto/request/CreateDiaryRequest.java
  backend/src/main/java/com/kongdak/controller/dto/request/DecorationCreateRequest.java
  backend/src/main/java/com/kongdak/controller/dto/request/DecorationUpdateRequest.java
  backend/src/main/java/com/kongdak/controller/dto/request/UpdateDiaryRequest.java
  backend/src/main/java/com/kongdak/controller/dto/response/AnswerEmojiResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/CoupleDisconnectResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/CoupleInfo.java
  backend/src/main/java/com/kongdak/controller/dto/response/CoupleResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/CoupleRestoreResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/DailyQuestionResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/DeactivateResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/DiaryDeleteResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/DiaryDetailResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/DiaryUpdateResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/MatchAcceptResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/MatchRejectResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/MatchRequestResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/MemberResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/ReplyCreateResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/ReplyDeleteResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/ScheduleDeleteResponse.java
  backend/src/main/java/com/kongdak/domain/calendar/CalendarService.java
  backend/src/main/java/com/kongdak/domain/couple/Couple.java
  backend/src/main/java/com/kongdak/domain/couple/CoupleRepository.java
  backend/src/main/java/com/kongdak/domain/couple/CoupleService.java
  backend/src/main/java/com/kongdak/domain/dailyquestion/DailyAnswerRepository.java
  backend/src/main/java/com/kongdak/domain/dailyquestion/DailyQuestionRepository.java
  backend/src/main/java/com/kongdak/domain/dailyquestion/DailyQuestionService.java
  backend/src/main/java/com/kongdak/domain/diary/Diary.java
  backend/src/main/java/com/kongdak/domain/diary/DiaryService.java
  backend/src/main/java/com/kongdak/domain/member/Member.java
  backend/src/main/java/com/kongdak/domain/member/MemberRepository.java
  backend/src/main/java/com/kongdak/domain/member/MemberService.java
  backend/src/main/java/com/kongdak/global/exception/ErrorCode.java
Labels: duplicate, enhancement

#65 데일리 질문과 캘린더 API 구조 개선 및 로직 최적화
  backend/src/main/java/com/kongdak/config/JacksonConfig.java
  backend/src/main/java/com/kongdak/controller/CalendarController.java
  backend/src/main/java/com/kongdak/controller/DailyQuestionController.java
  backend/src/main/java/com/kongdak/controller/dto/response/DailyAnswerResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/DailyQuestionListResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/DailyQuestionWithAnswersResponse.java
  backend/src/main/java/com/kongdak/domain/calendar/CalendarService.java
  backend/src/main/java/com/kongdak/domain/dailyquestion/DailyAnswerRepository.java
  backend/src/main/java/com/kongdak/domain/dailyquestion/DailyQuestionRepository.java
  backend/src/main/java/com/kongdak/domain/dailyquestion/DailyQuestionService.java
Labels: duplicate, enhancement

#66 검색을 통한 지도 마킹 기능 개발
  backend/src/main/java/com/kongdak/controller/MapController.java
  backend/src/main/java/com/kongdak/controller/dto/response/KakaoLocalSearchResponse.java
  frontend/android/app/build.gradle
  frontend/android/app/src/main/AndroidManifest.xml
  frontend/app/calenderregist/index.tsx
  frontend/assets/apis/maps.ts
  frontend/assets/types/map/mapModels.ts
  frontend/assets/utils/locationPermission.ts
  frontend/components/ui/MapScreen.tsx
  frontend/components/ui/MapSearchBar.tsx
  frontend/hooks/useSearch.ts
  frontend/package-lock.json
  frontend/package.json
Labels: documentation

#69 MapScreen 충돌 해결
  frontend/assets/utils/http-common.ts
  frontend/components/ui/MapScreen.tsx
Labels: duplicate

#71 일정 데이터 연결 및 데이터 표시
  frontend/app/(tabs)/calendar/index.tsx
  frontend/assets/dummydata/calandarmonthlist.json
  frontend/assets/types/calendar/calendarModels.ts
  frontend/assets/utils/calendar.ts
Labels: enhancement

#73 캘린더 상세정보 컴포넌트 생성
  frontend/app/(tabs)/calendar/index.tsx
  frontend/app/calenderregist/index.tsx
  frontend/assets/types/calendar/calendarModels.ts
  frontend/assets/types/calendar/calendarUI.ts
  frontend/assets/utils/calendar.ts
  frontend/assets/utils/getWeekday.ts
  frontend/components/ui/CalendarDetailList.tsx
Labels: enhancement

#74 데일리 질문, 다이어리 목록 조회 방식 변경, Soft Delete 구현
  backend/src/main/java/com/kongdak/controller/DailyQuestionController.java
  backend/src/main/java/com/kongdak/controller/DiaryController.java
  backend/src/main/java/com/kongdak/controller/dto/response/AnswerReplyResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/DailyAnswerResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/DailyQuestionWithAnswersResponse.java
  backend/src/main/java/com/kongdak/controller/dto/response/SearchDiaryResponse.java
  backend/src/main/java/com/kongdak/domain/BaseTimeEntity.java
  backend/src/main/java/com/kongdak/domain/calendar/CalendarService.java
  backend/src/main/java/com/kongdak/domain/couple/CoupleService.java
  backend/src/main/java/com/kongdak/domain/dailyquestion/AnswerReplyRepository.java
  backend/src/main/java/com/kongdak/domain/dailyquestion/DailyAnswer.java
  backend/src/main/java/com/kongdak/domain/dailyquestion/DailyAnswerRepository.java
  backend/src/main/java/com/kongdak/domain/dailyquestion/DailyQuestionRepository.java
  backend/src/main/java/com/kongdak/domain/dailyquestion/DailyQuestionService.java
  backend/src/main/java/com/kongdak/domain/diary/DiaryRepository.java
  backend/src/main/java/com/kongdak/domain/diary/DiaryService.java
Labels: enhancement

#76 사용자가 보고 있는 지도 중심 좌표에서 주변 검색 기능 구현
  frontend/android/app/src/main/AndroidManifest.xml
  frontend/app/(tabs)/calendar/index.tsx
  frontend/app/calenderregist/index.tsx
  frontend/app/index.tsx
  frontend/assets/utils/map.ts
  frontend/components/ui/MapScreen.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: documentation

#77 캘린더, 스케줄 테스트 작성
  backend/src/main/java/com/kongdak/controller/CalendarController.java
  backend/src/main/java/com/kongdak/controller/DiaryController.java
  backend/src/main/java/com/kongdak/controller/MemberController.java
  backend/src/main/java/com/kongdak/controller/dto/request/DiaryUpdateRequest.java
  backend/src/main/java/com/kongdak/controller/dto/request/NicknameUpdateRequest.java
  backend/src/main/java/com/kongdak/controller/dto/request/ScheduleUpdateRequest.java
  backend/src/main/java/com/kongdak/domain/calendar/CalendarService.java
  backend/src/main/java/com/kongdak/domain/calendar/HolidayRepository.java
  backend/src/main/java/com/kongdak/domain/diary/DiaryService.java
  backend/src/test/java/com/kongdak/domain/calendar/CalendarServiceTest.java
Labels: enhancement
