Repository kong-dak/kong-dak, pull requests merged in 2025-03, with the labels that each got.

#112 버킷리스트 백사이드 구현
  backend/src/main/java/com/kongdak/controller/BucketListController.java
  backend/src/main/java/com/kongdak/controller/dto/request/BucketListCreateDto.java
  backend/src/main/java/com/kongdak/controller/dto/request/BucketListReorderRequestDto.java
  backend/src/main/java/com/kongdak/controller/dto/request/BucketListUpdateDto.java
  backend/src/main/java/com/kongdak/controller/dto/response/BucketListDeleteResponseDto.java
  backend/src/main/java/com/kongdak/controller/dto/response/BucketListReorderResponseDto.java
  backend/src/main/java/com/kongdak/controller/dto/response/BucketListResponseDto.java
  backend/src/main/java/com/kongdak/domain/bucketlist/BucketList.java
  backend/src/main/java/com/kongdak/domain/bucketlist/BucketListCategory.java
  backend/src/main/java/com/kongdak/domain/bucketlist/BucketListRepository.java
  backend/src/main/java/com/kongdak/domain/bucketlist/BucketListService.java
  backend/src/main/java/com/kongdak/domain/couple/CoupleService.java
  backend/src/main/java/com/kongdak/global/exception/ErrorCode.java
Labels: enhancement

#116 버킷리스트 생성자 수정
  backend/src/main/java/com/kongdak/domain/bucketlist/BucketList.java
Labels: bug

#117 fix: 버킷리스트 생성자 수정
  backend/src/main/java/com/kongdak/controller/BucketListController.java
Labels: bug

#119 로그인 시 유저 활성화 상태 체크 삭제
  backend/src/main/java/com/kongdak/controller/dto/response/CoupleResponse.java
  backend/src/main/java/com/kongdak/global/security/jwt/sdk/SocialLoginService.java
Labels: bug

#121 버킷리스트 엔드포인트 에러 수정 및 MemberResponse 에 파트너 Nickname 추가
  backend/src/main/java/com/kongdak/controller/BucketListController.java
  backend/src/main/java/com/kongdak/controller/dto/response/MemberResponse.java
Labels: bug

#122 MemberResponse NullPointer Exception 처리
  backend/src/main/java/com/kongdak/controller/dto/response/MemberResponse.java
Labels: bug

#123 설정 탭 구현
  frontend/app/(tabs)/bucket/index.tsx
  frontend/app/(tabs)/index.tsx
  frontend/app/login/_layout.tsx
  frontend/app/login/kakao.tsx
  frontend/app/login/restoreUser.tsx
  frontend/app/set/_layout.tsx
  frontend/app/set/changeNick.tsx
  frontend/app/set/connectCouple.tsx
  frontend/app/set/index.tsx
  frontend/app/set/manageCouple.tsx
  frontend/app/set/manageUser.tsx
  frontend/app/set/withdrawUser.tsx
  frontend/assets/apis/bucketlist.ts
  frontend/assets/apis/couples.ts
  frontend/assets/apis/members.ts
  frontend/assets/utils/http-common.ts
  frontend/components/common/HeaderIcons.tsx
  frontend/components/ui/SettingItem.tsx
Labels: documentation

#124 bucket list 순서 관련 에러 수정
  backend/src/main/java/com/kongdak/domain/bucketlist/BucketListRepository.java
  backend/src/main/java/com/kongdak/domain/bucketlist/BucketListService.java
Labels: bug, enhancement

#125 S3 도입 및 사진 업로드 엔드포인트 추가
  backend/build.gradle
  backend/src/main/java/com/kongdak/config/AwsS3Config.java
  backend/src/main/java/com/kongdak/controller/DiaryController.java
  backend/src/main/java/com/kongdak/controller/dto/response/DiaryPhotoUploadResponse.java
  backend/src/main/java/com/kongdak/global/S3/S3Service.java
  backend/src/main/java/com/kongdak/global/exception/ErrorCode.java
Labels: enhancement

#126 버킷리스트 API 연결
  frontend/android/app/build.gradle
  frontend/android/app/google-services.json
  frontend/android/build.gradle
  frontend/android/gradle.properties
  frontend/app/(tabs)/bucket/index.tsx
  frontend/app/index.tsx
  frontend/assets/apis/bucketlist.ts
  frontend/assets/dummydata/bucketlist.json
  frontend/assets/types/type.ts
  frontend/assets/utils/http-common.ts
  frontend/components/ui/BucketInputBox.tsx
  frontend/components/ui/BucketView.tsx
  frontend/components/ui/DragItem.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: documentation

#129 FCM 포어그라운드, 백그라운드 작업
  frontend/.gitignore
  frontend/android/app/build.gradle
  frontend/android/app/src/main/AndroidManifest.xml
  frontend/android/gradle.properties
  frontend/app/index.tsx
  frontend/assets/types/type.ts
  frontend/package-lock.json
  frontend/package.json
Labels: documentation

#133 알람, SSE 도입
  backend/src/main/java/com/kongdak/controller/MemberController.java
  backend/src/main/java/com/kongdak/controller/NotificationController.java
  backend/src/main/java/com/kongdak/domain/bucketlist/event/BucketCompletedEvent.java
  backend/src/main/java/com/kongdak/domain/bucketlist/event/BucketCreatedEvent.java
  backend/src/main/java/com/kongdak/domain/calendar/event/ScheduleCreatedEvent.java
  backend/src/main/java/com/kongdak/domain/calendar/event/ScheduleReminderEvent.java
  backend/src/main/java/com/kongdak/domain/calendar/event/ScheduleUpdatedEvent.java
  backend/src/main/java/com/kongdak/domain/couple/event/CoupleAnniversaryEvent.java
  backend/src/main/java/com/kongdak/domain/couple/event/CoupleMatchAcceptedEvent.java
  backend/src/main/java/com/kongdak/domain/couple/event/CoupleMatchRejectedEvent.java
  backend/src/main/java/com/kongdak/domain/couple/event/CoupleMatchRequestedEvent.java
  backend/src/main/java/com/kongdak/domain/couple/service/CoupleService.java
  backend/src/main/java/com/kongdak/domain/dailyquestion/event/DailyQuestionAnsweredEvent.java
  backend/src/main/java/com/kongdak/domain/dailyquestion/event/DailyQuestionNewEvent.java
  backend/src/main/java/com/kongdak/domain/dailyquestion/event/DailyQuestionRepliedEvent.java
  backend/src/main/java/com/kongdak/domain/diary/event/DiaryCreatedEvent.java
  backend/src/main/java/com/kongdak/domain/diary/event/DiaryEmojiEvent.java
  backend/src/main/java/com/kongdak/domain/member/dto/response/MemberNicknameChangeResponse.java
  backend/src/main/java/com/kongdak/domain/notification/NotificationMessage.java
  backend/src/main/java/com/kongdak/domain/notification/NotificationType.java
  backend/src/main/java/com/kongdak/domain/notification/SseEmitterService.java
  backend/src/main/java/com/kongdak/domain/notification/dto/response/NotificationListResponse.java
  backend/src/main/java/com/kongdak/domain/notification/dto/response/NotificationResponse.java
  backend/src/main/java/com/kongdak/domain/notification/entity/NotificationEvent.java
  backend/src/main/java/com/kongdak/domain/notification/entity/NotificationType.java
  backend/src/main/java/com/kongdak/domain/notification/event/NotificationEventListener.java
  backend/src/main/java/com/kongdak/domain/notification/repository/NotificationRepository.java
  backend/src/main/java/com/kongdak/domain/notification/service/NotificationService.java
  backend/src/main/java/com/kongdak/global/config/EventConfig.java
  backend/src/main/java/com/kongdak/global/event/DomainEvent.java
  backend/src/main/java/com/kongdak/global/event/EventPublisher.java
  backend/src/main/java/com/kongdak/global/event/SpringEventPublisher.java
Labels: enhancement

#134 콕찌르기 추가
  backend/src/main/java/com/kongdak/domain/notification/entity/NotificationType.java
Labels: enhancement

#135 레이아웃 리디자인
  frontend/android/app/src/main/AndroidManifest.xml
  frontend/app/(tabs)/calendar/index.tsx
  frontend/app/(tabs)/diary/index.tsx
  frontend/app/(tabs)/index.tsx
  frontend/app/login/index.tsx
  frontend/app/login/setnick.tsx
  frontend/app/write/index.tsx
  frontend/components/ui/CalendarDetailList.tsx
  frontend/components/ui/DiaryItem.tsx
Labels: documentation

#136 S3 fileKey 직접 받는 방식으로 변경
  backend/src/main/java/com/kongdak/controller/DiaryController.java
  backend/src/main/java/com/kongdak/domain/diary/S3/S3Service.java
  backend/src/main/resources/logback-spring.xml
Labels: enhancement

#137 S3 key 반환 방식 및 photo URL 길이 변경
  backend/src/main/java/com/kongdak/controller/DiaryController.java
  backend/src/main/java/com/kongdak/domain/diary/dto/request/CreateDiaryRequest.java
  backend/src/main/java/com/kongdak/domain/diary/dto/response/DiaryDetailResponse.java
  backend/src/main/java/com/kongdak/domain/diary/dto/response/DiaryPhotoUploadResponse.java
  backend/src/main/java/com/kongdak/domain/diary/entity/DiaryPhoto.java
  backend/src/main/java/com/kongdak/domain/diary/service/DiaryService.java
Labels: bug, duplicate

#138 photoUrl 보낼때 원본(db) 과 S3 presigned version 함께 보내는 방식으로 변경
  backend/src/main/java/com/kongdak/domain/calendar/dto/response/PhotoResponse.java
  backend/src/main/java/com/kongdak/domain/diary/service/DiaryService.java
Labels: bug, enhancement

#139 일기 이미지 기능 수정
  frontend/app/write/index.tsx
  frontend/assets/apis/diary.ts
  frontend/package-lock.json
  frontend/package.json
Labels: documentation

#140 NotificationController 내 userDetails 사용방식 변경
  backend/src/main/java/com/kongdak/controller/NotificationController.java
Labels: bug

#141 알림(SSE) 구현 및 서비스 확장
  backend/src/main/java/com/kongdak/controller/CalendarController.java
  backend/src/main/java/com/kongdak/domain/bucketlist/service/BucketListService.java
  backend/src/main/java/com/kongdak/domain/calendar/service/CalendarService.java
  backend/src/main/java/com/kongdak/domain/couple/service/CoupleService.java
  backend/src/main/java/com/kongdak/domain/dailyquestion/service/DailyQuestionService.java
  backend/src/main/java/com/kongdak/domain/diary/service/DiaryService.java
  backend/src/main/java/com/kongdak/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/kongdak/domain/member/service/MemberService.java
  backend/src/main/java/com/kongdak/domain/notification/entity/NotificationEvent.java
  backend/src/main/java/com/kongdak/domain/notification/entity/NotificationType.java
  backend/src/main/java/com/kongdak/domain/notification/service/NotificationService.java
Labels: enhancement

#142 테스트용 알림 조회 엔드포인트 추가
  backend/src/main/java/com/kongdak/controller/NotificationController.java
Labels: enhancement

#143 지도 고도화: 리뷰
  backend/src/main/java/com/kongdak/controller/MapController.java
  backend/src/main/java/com/kongdak/domain/map/MapRepository.java
  backend/src/main/java/com/kongdak/domain/map/MapService.java
  backend/src/main/java/com/kongdak/domain/map/Place.java
  backend/src/main/java/com/kongdak/domain/map/PlaceImage.java
  backend/src/main/java/com/kongdak/domain/map/PlaceImageRepository.java
  backend/src/main/java/com/kongdak/domain/map/PlaceOperatingHour.java
  backend/src/main/java/com/kongdak/domain/map/PlaceOperatingHourRepository.java
  backend/src/main/java/com/kongdak/domain/map/PlaceReview.java
  backend/src/main/java/com/kongdak/domain/map/PlaceReviewRepository.java
  backend/src/main/java/com/kongdak/domain/map/dto/request/CreateReviewRequest.java
  backend/src/main/java/com/kongdak/domain/map/dto/request/UpdateReviewRequest.java
  backend/src/main/java/com/kongdak/domain/map/dto/response/KakaoLocalSearchResponse.java
  backend/src/main/java/com/kongdak/domain/map/dto/response/PagedReviewResponse.java
  backend/src/main/java/com/kongdak/domain/map/dto/response/PlaceDetailResponse.java
  backend/src/main/java/com/kongdak/domain/map/dto/response/PlaceImageResponse.java
  backend/src/main/java/com/kongdak/domain/map/dto/response/PlaceOperatingHourResponse.java
  backend/src/main/java/com/kongdak/domain/map/dto/response/PlaceReviewDeleteResponse.java
  backend/src/main/java/com/kongdak/domain/map/dto/response/PlaceReviewResponse.java
  backend/src/main/java/com/kongdak/global/exception/ErrorCode.java
  backend/src/main/java/com/kongdak/global/redis/RedisPlaceRepository.java
  docker-compose.yml
  frontend/Dockerfile
  frontend/app/calenderregist/index.tsx
  frontend/assets/apis/maps.ts
  frontend/assets/types/map/mapModels.ts
  frontend/components/ui/MapScreen.tsx
  frontend/components/ui/PlaceDetailModal.tsx
  frontend/components/ui/PlaceHomeTab.tsx
  frontend/components/ui/PlaceInfo.tsx
  frontend/components/ui/ReviewCreateModal.tsx
  frontend/components/ui/ReviewTab.tsx
Labels: documentation
